### ISSUE TITLE
Function calls are not supported in decorators but 'TranslateTestingModule' was called.

### ISSUE THREAD

**Issue by michal-husak** [mwootendev/ngx-translate-plugins#21] opened 2020-09-30 09:35 UTC
Hey,

I am trying to use your `TranslateTestingModule ` in one of my modules `TranslationTestHelperModule`:

```typescript
declare var require: any
const TRANSLATIONS_EN = require('../../assets/i18n/en.json');
const TRANSLATIONS_DE = require('../../assets/i18n/de.json');

@NgModule({
  imports: [
    HttpClientTestingModule,
    TranslateTestingModule
      .withTranslations('de', TRANSLATIONS_DE)
      .withTranslations('en', TRANSLATIONS_EN)
      .withDefaultLanguage('de')
  ]
})
export class TranslationTestHelperModule { }
```
For running the tests it works great, but when I tried to build the project it throws an error:
```
ERROR in Error during template compile of 'TranslationTestHelperModule'
  Function calls are not supported in decorators but 'TranslateTestingModule' was called.
```
My `TranslationTestHelperModule` is used just in the `.spec.ts` files.

My dependencies:
```
"@angular/core": "^10.1.3"
"@ngx-translate/core": "^13.0.0"
```

dev dependencies:
`"ngx-translate-testing": "^5.0.0"`

Any idea how to make the build running?

Thank you.

**Comment by mwootendev** [comment] 2020-10-20 15:35
@michal-husak , do you happen to have a sample repository? Just to be clear, `ng run test` is successful but `ng build` is failing? Are there any specific build parameters you are using (AoT, build optimizer, etc.)?

**Comment by mwootendev** [comment] 2021-07-19 14:05
Closing as unable to reproduce.

**Closed as completed by mwootendev** 2021-07-19 14:05 UTC
